name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # Increase memory allocation to prevent memory-related issues
        # This example sets the memory allocation to 4GB
        # You can adjust the value as needed
        node-options: '--max-old-space-size=4096'
    - run: npm cache clean --force
    - run: npm ci
    - run: npm run build
    - run: npm test
