name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        node-options: '--max-old-space-size=4096'

    - name: List Directories
      run: ls -r

    - name: Change directory to back
      run: cd back; ls

    - run: cd back; npm install

    - name: Verify database connection
      run: cd back; node ./scripts/verify-db-connection.js

    - name: Build Angular app
      run: cd admin; npm install

    - name: Run ng serve and capture stdout
      run: cd admin && npm run start > stdout.log 2>&1 & sleep 10

    - name: Upload stdout log
      uses: actions/upload-artifact@v2
      with:
        name: stdout-log
        path: back/stdout.log
