name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        node-options: '--max-old-space-size=4096'
    - name: List Directories
      run: ls -r
    - name: Change directory to back
      run: cd back
    - run: npm install
    - run: npm start
    - run:
        npm cache clean --force
        yarn cache clean --force
